#![allow(clippy::approx_constant, clippy::excessive_precision, clippy::vec_init_then_push)]

use super::facts::{Fact, Domain};

pub fn all_facts() -> Vec<Fact> {
    let mut f = Vec::new();

    // ===== ALPHA — Mathematics & Logic (400+ facts) =====
    f.push(Fact::new("pi", 3.141592653589793, "", "math constant"));
    f.push(Fact::new("e", 2.718281828459045, "", "math constant"));
    f.push(Fact::new("sqrt2", 1.4142135623730951, "", "math constant"));
    f.push(Fact::new("ln2", 0.6931471805599453, "", "math constant"));
    f.push(Fact::new("ln10", 2.302585092994046, "", "math constant"));
    f.push(Fact::new("phi", 1.618033988749895, "", "golden ratio"));
    f.push(Fact::new("euler_mascheroni", 0.5772156649015329, "", "Euler-Mascheroni constant"));
    f.push(Fact::new("catalan_constant", 0.915965594177219, "", "Catalan's constant"));
    f.push(Fact::new("apery_constant", 1.202056903159594, "", "Apéry's constant ζ(3)"));
    f.push(Fact::new("khinchin_constant", 2.685452001065306, "", "Khinchin constant"));
    f.push(Fact::new("feigenbaum_delta", 4.66920160910299, "", "Feigenbaum constant δ"));
    f.push(Fact::new("feigenbaum_alpha", 2.502907875095892, "", "Feigenbaum constant α"));
    f.push(Fact::new("champernowne", 0.123456789101112, "", "Champernowne constant C10"));
    f.push(Fact::new("gauss_constant", 0.834626841674073, "", "Gauss constant"));
    f.push(Fact::new("omega_constant", 0.567143290409783, "", "Omega constant W(1)"));
    f.push(Fact::new("twin_prime", 1.902160583104, "", "twin prime constant"));
    f.push(Fact::new("mill_constant", 1.30637788386308, "", "Mills constant"));
    f.push(Fact::new("ramanujan_soldner", 1.451369234883381, "", "Ramanujan-Soldner constant"));
    f.push(Fact::new("golomb_dickman", 0.62432998854355, "", "Golomb-Dickman constant"));
    f.push(Fact::new("viswanath_constant", 1.13198824, "", "Viswanath constant"));
    f.push(Fact::new("lemniscate_constant", 2.622057554292119, "", "lemniscate constant"));
    f.push(Fact::new("glaisher_constant", 1.282427129100622, "", "Glaisher-Kinkelin constant"));
    f.push(Fact::new("pi_squared", 9.869604401089358, "", "π²"));
    f.push(Fact::new("e_squared", 7.38905609893065, "", "e²"));
    f.push(Fact::new("sqrt_pi", 1.772453850905516, "", "√π"));
    f.push(Fact::new("sqrt_e", 1.6487212707001282, "", "√e"));
    f.push(Fact::new("degrees_to_radians", 0.017453292519943295, "", "1° in radians"));
    f.push(Fact::new("radians_to_degrees", 57.29577951308232, "", "1 rad in degrees"));
    f.push(Fact::new("zero_factorial", 1.0, "", "0! = 1"));
    f.push(Fact::new("googol", 1e+100, "", "10^100"));
    f.push(Fact::new("log10_e", 0.4342944819032518, "", "log10(e)"));
    f.push(Fact::new("log10_2", 0.3010299956639812, "", "log10(2)"));
    f.push(Fact::new("log2_e", 1.4426950408889634, "", "log2(e)"));
    f.push(Fact::new("log2_10", 3.3219280948873626, "", "log2(10)"));

    // === Number theory ===
    f.push(Fact::new("mersenne_1", 2.0, "", "M2"));
    f.push(Fact::new("mersenne_2", 3.0, "", "M3"));
    f.push(Fact::new("mersenne_3", 5.0, "", "M5"));
    f.push(Fact::new("mersenne_4", 7.0, "", "M7"));
    f.push(Fact::new("mersenne_5", 13.0, "", "M13"));
    f.push(Fact::new("mersenne_6", 17.0, "", "M17"));
    f.push(Fact::new("mersenne_7", 19.0, "", "M19"));
    f.push(Fact::new("mersenne_8", 31.0, "", "M31"));
    f.push(Fact::new("mersenne_9", 61.0, "", "M61"));
    f.push(Fact::new("mersenne_10", 89.0, "", "M89"));
    f.push(Fact::new("mersenne_11", 107.0, "", "M107"));
    f.push(Fact::new("mersenne_12", 127.0, "", "M127"));
    f.push(Fact::new("mersenne_13", 521.0, "", "M521"));
    f.push(Fact::new("mersenne_14", 607.0, "", "M607"));
    f.push(Fact::new("mersenne_15", 1279.0, "", "M1279"));
    f.push(Fact::new("mersenne_16", 2203.0, "", "M2203"));
    f.push(Fact::new("mersenne_17", 2281.0, "", "M2281"));
    f.push(Fact::new("mersenne_18", 3217.0, "", "M3217"));
    f.push(Fact::new("mersenne_19", 4253.0, "", "M4253"));
    f.push(Fact::new("mersenne_20", 4423.0, "", "M4423"));
    f.push(Fact::new("mersenne_21", 9689.0, "", "M9689"));
    f.push(Fact::new("mersenne_22", 9941.0, "", "M9941"));
    f.push(Fact::new("mersenne_23", 11213.0, "", "M11213"));
    f.push(Fact::new("mersenne_24", 19937.0, "", "M19937"));
    f.push(Fact::new("mersenne_25", 21701.0, "", "M21701"));
    f.push(Fact::new("mersenne_26", 23209.0, "", "M23209"));
    f.push(Fact::new("mersenne_27", 44497.0, "", "M44497"));
    f.push(Fact::new("mersenne_28", 86243.0, "", "M86243"));
    f.push(Fact::new("mersenne_29", 110503.0, "", "M110503"));
    f.push(Fact::new("mersenne_30", 132049.0, "", "M132049"));
    f.push(Fact::new("perfect_1", 6.0, "", "perfect #1"));
    f.push(Fact::new("perfect_2", 28.0, "", "perfect #2"));
    f.push(Fact::new("perfect_3", 496.0, "", "perfect #3"));
    f.push(Fact::new("perfect_4", 8128.0, "", "perfect #4"));
    f.push(Fact::new("perfect_5", 33550336.0, "", "perfect #5"));
    f.push(Fact::new("perfect_6", 8589869056.0, "", "perfect #6"));
    f.push(Fact::new("perfect_7", 137438691328.0, "", "perfect #7"));
    f.push(Fact::new("perfect_8", 2.305843008139952e+18, "", "perfect #8"));
    f.push(Fact::new("prime_1", 2.0, "", "prime #1"));
    f.push(Fact::new("prime_2", 3.0, "", "prime #2"));
    f.push(Fact::new("prime_3", 5.0, "", "prime #3"));
    f.push(Fact::new("prime_4", 7.0, "", "prime #4"));
    f.push(Fact::new("prime_5", 11.0, "", "prime #5"));
    f.push(Fact::new("prime_6", 13.0, "", "prime #6"));
    f.push(Fact::new("prime_7", 17.0, "", "prime #7"));
    f.push(Fact::new("prime_8", 19.0, "", "prime #8"));
    f.push(Fact::new("prime_9", 23.0, "", "prime #9"));
    f.push(Fact::new("prime_10", 29.0, "", "prime #10"));
    f.push(Fact::new("prime_11", 31.0, "", "prime #11"));
    f.push(Fact::new("prime_12", 37.0, "", "prime #12"));
    f.push(Fact::new("prime_13", 41.0, "", "prime #13"));
    f.push(Fact::new("prime_14", 43.0, "", "prime #14"));
    f.push(Fact::new("prime_15", 47.0, "", "prime #15"));
    f.push(Fact::new("prime_16", 53.0, "", "prime #16"));
    f.push(Fact::new("prime_17", 59.0, "", "prime #17"));
    f.push(Fact::new("prime_18", 61.0, "", "prime #18"));
    f.push(Fact::new("prime_19", 67.0, "", "prime #19"));
    f.push(Fact::new("prime_20", 71.0, "", "prime #20"));
    f.push(Fact::new("prime_21", 73.0, "", "prime #21"));
    f.push(Fact::new("prime_22", 79.0, "", "prime #22"));
    f.push(Fact::new("prime_23", 83.0, "", "prime #23"));
    f.push(Fact::new("prime_24", 89.0, "", "prime #24"));
    f.push(Fact::new("prime_25", 97.0, "", "prime #25"));
    f.push(Fact::new("prime_26", 101.0, "", "prime #26"));
    f.push(Fact::new("prime_27", 103.0, "", "prime #27"));
    f.push(Fact::new("prime_28", 107.0, "", "prime #28"));
    f.push(Fact::new("prime_29", 109.0, "", "prime #29"));
    f.push(Fact::new("prime_30", 113.0, "", "prime #30"));
    f.push(Fact::new("fib_1", 1.0, "", "F1"));
    f.push(Fact::new("fib_2", 1.0, "", "F2"));
    f.push(Fact::new("fib_3", 2.0, "", "F3"));
    f.push(Fact::new("fib_4", 3.0, "", "F4"));
    f.push(Fact::new("fib_5", 5.0, "", "F5"));
    f.push(Fact::new("fib_6", 8.0, "", "F6"));
    f.push(Fact::new("fib_7", 13.0, "", "F7"));
    f.push(Fact::new("fib_8", 21.0, "", "F8"));
    f.push(Fact::new("fib_9", 34.0, "", "F9"));
    f.push(Fact::new("fib_10", 55.0, "", "F10"));
    f.push(Fact::new("fib_11", 89.0, "", "F11"));
    f.push(Fact::new("fib_12", 144.0, "", "F12"));
    f.push(Fact::new("fib_13", 233.0, "", "F13"));
    f.push(Fact::new("fib_14", 377.0, "", "F14"));
    f.push(Fact::new("fib_15", 610.0, "", "F15"));
    f.push(Fact::new("fib_16", 987.0, "", "F16"));
    f.push(Fact::new("fib_17", 1597.0, "", "F17"));
    f.push(Fact::new("fib_18", 2584.0, "", "F18"));
    f.push(Fact::new("fib_19", 4181.0, "", "F19"));
    f.push(Fact::new("fib_20", 6765.0, "", "F20"));
    f.push(Fact::new("fib_21", 10946.0, "", "F21"));
    f.push(Fact::new("fib_22", 17711.0, "", "F22"));
    f.push(Fact::new("fib_23", 28657.0, "", "F23"));
    f.push(Fact::new("fib_24", 46368.0, "", "F24"));
    f.push(Fact::new("fib_25", 75025.0, "", "F25"));
    f.push(Fact::new("fib_26", 121393.0, "", "F26"));
    f.push(Fact::new("fib_27", 196418.0, "", "F27"));
    f.push(Fact::new("fib_28", 317811.0, "", "F28"));
    f.push(Fact::new("fib_29", 514229.0, "", "F29"));
    f.push(Fact::new("fib_30", 832040.0, "", "F30"));
    f.push(Fact::new("catalan_1", 1.0, "", "C1"));
    f.push(Fact::new("catalan_2", 1.0, "", "C2"));
    f.push(Fact::new("catalan_3", 2.0, "", "C3"));
    f.push(Fact::new("catalan_4", 5.0, "", "C4"));
    f.push(Fact::new("catalan_5", 14.0, "", "C5"));
    f.push(Fact::new("catalan_6", 42.0, "", "C6"));
    f.push(Fact::new("catalan_7", 132.0, "", "C7"));
    f.push(Fact::new("catalan_8", 429.0, "", "C8"));
    f.push(Fact::new("catalan_9", 1430.0, "", "C9"));
    f.push(Fact::new("catalan_10", 4862.0, "", "C10"));
    f.push(Fact::new("catalan_11", 16796.0, "", "C11"));
    f.push(Fact::new("catalan_12", 58786.0, "", "C12"));
    f.push(Fact::new("catalan_13", 208012.0, "", "C13"));
    f.push(Fact::new("catalan_14", 742900.0, "", "C14"));
    f.push(Fact::new("catalan_15", 2674440.0, "", "C15"));
    f.push(Fact::new("catalan_16", 9694845.0, "", "C16"));
    f.push(Fact::new("catalan_17", 35357670.0, "", "C17"));
    f.push(Fact::new("catalan_18", 129644790.0, "", "C18"));
    f.push(Fact::new("catalan_19", 477638700.0, "", "C19"));
    f.push(Fact::new("catalan_20", 1767263190.0, "", "C20"));
    f.push(Fact::new("fact_0", 1.0, "", "0!"));
    f.push(Fact::new("fact_1", 1.0, "", "1!"));
    f.push(Fact::new("fact_2", 2.0, "", "2!"));
    f.push(Fact::new("fact_3", 6.0, "", "3!"));
    f.push(Fact::new("fact_4", 24.0, "", "4!"));
    f.push(Fact::new("fact_5", 120.0, "", "5!"));
    f.push(Fact::new("fact_6", 720.0, "", "6!"));
    f.push(Fact::new("fact_7", 5040.0, "", "7!"));
    f.push(Fact::new("fact_8", 40320.0, "", "8!"));
    f.push(Fact::new("fact_9", 362880.0, "", "9!"));
    f.push(Fact::new("fact_10", 3628800.0, "", "10!"));
    f.push(Fact::new("fact_11", 39916800.0, "", "11!"));
    f.push(Fact::new("fact_12", 479001600.0, "", "12!"));
    f.push(Fact::new("fact_13", 6227020800.0, "", "13!"));
    f.push(Fact::new("fact_14", 87178291200.0, "", "14!"));

    // === Geometry ===
    f.push(Fact::new("circle_360_deg", 360.0, "°", "circle degrees"));
    f.push(Fact::new("triangle_180_deg", 180.0, "°", "triangle sum"));
    f.push(Fact::new("sphere_solid_angle", 4.0, "π sr", "sphere steradians"));
    f.push(Fact::new("platonic_solids", 5.0, "", "Platonic solids"));
    f.push(Fact::new("archimedean_solids", 13.0, "", "Archimedean solids"));
    f.push(Fact::new("platonic_tetrahedron_faces", 4.0, "", "tetrahedron faces"));
    f.push(Fact::new("platonic_tetrahedron_vertices", 4.0, "", "tetrahedron vertices"));
    f.push(Fact::new("platonic_tetrahedron_edges", 6.0, "", "tetrahedron edges"));
    f.push(Fact::new("platonic_cube_faces", 6.0, "", "cube faces"));
    f.push(Fact::new("platonic_cube_vertices", 8.0, "", "cube vertices"));
    f.push(Fact::new("platonic_cube_edges", 12.0, "", "cube edges"));
    f.push(Fact::new("platonic_octahedron_faces", 8.0, "", "octahedron faces"));
    f.push(Fact::new("platonic_octahedron_vertices", 6.0, "", "octahedron vertices"));
    f.push(Fact::new("platonic_octahedron_edges", 12.0, "", "octahedron edges"));
    f.push(Fact::new("platonic_dodecahedron_faces", 12.0, "", "dodecahedron faces"));
    f.push(Fact::new("platonic_dodecahedron_vertices", 20.0, "", "dodecahedron vertices"));
    f.push(Fact::new("platonic_dodecahedron_edges", 30.0, "", "dodecahedron edges"));
    f.push(Fact::new("platonic_icosahedron_faces", 20.0, "", "icosahedron faces"));
    f.push(Fact::new("platonic_icosahedron_vertices", 12.0, "", "icosahedron vertices"));
    f.push(Fact::new("platonic_icosahedron_edges", 30.0, "", "icosahedron edges"));
    f.push(Fact::new("euclid_postulates", 5.0, "", "Euclidean geometry postulates"));

    // === Calculus ===
    f.push(Fact::new("derivative_of_x_squared", 2.0, "", "d/dx x^2 at x=1"));
    f.push(Fact::new("derivative_of_sin", 0.0, "", "d/dx sin(x) at x=0"));
    f.push(Fact::new("derivative_of_cos", -1.0, "", "d/dx cos(x) at x=0"));
    f.push(Fact::new("integral_0_to_1_x_squared", 0.3333333333333333, "", "∫₀¹ x² dx"));
    f.push(Fact::new("integral_0_to_inf_e_x", 1.0, "", "∫₀^∞ e⁻ˣ dx"));
    f.push(Fact::new("gaussian_integral", 1.772453850905516, "", "∫_{-∞}^{∞} e^{-x²} dx"));
    f.push(Fact::new("gamma_1", 1.0, "", "Γ(1)"));
    f.push(Fact::new("gamma_2", 1.0, "", "Γ(2)"));
    f.push(Fact::new("gamma_3", 2.0, "", "Γ(3)"));
    f.push(Fact::new("gamma_4", 6.0, "", "Γ(4)"));
    f.push(Fact::new("gamma_5", 24.0, "", "Γ(5)"));
    f.push(Fact::new("gamma_6", 120.0, "", "Γ(6)"));
    f.push(Fact::new("gamma_7", 720.0, "", "Γ(7)"));
    f.push(Fact::new("gamma_8", 5040.0, "", "Γ(8)"));
    f.push(Fact::new("gamma_9", 40320.0, "", "Γ(9)"));
    f.push(Fact::new("gamma_10", 362880.0, "", "Γ(10)"));
    f.push(Fact::new("zeta_2", 1.6449340668482264, "", "ζ(2)"));
    f.push(Fact::new("zeta_4", 1.082323233711138, "", "ζ(4)"));
    f.push(Fact::new("zeta_6", 1.017343061984449, "", "ζ(6)"));
    f.push(Fact::new("zeta_8", 1.004077356197944, "", "ζ(8)"));
    f.push(Fact::new("zeta_10", 1.000994575127818, "", "ζ(10)"));
    f.push(Fact::new("harmonic_10", 2.9289682539682538, "", "H_10"));
    f.push(Fact::new("harmonic_100", 5.187377517639621, "", "H_100"));
    f.push(Fact::new("harmonic_1000", 7.485470860550345, "", "H_1000"));

    // === Trigonometry ===
    f.push(Fact::new("sin_0", 0.0, "", "sin(0°)"));
    f.push(Fact::new("cos_0", 1.0, "", "cos(0°)"));
    f.push(Fact::new("sin_30", 0.5, "", "sin(30°)"));
    f.push(Fact::new("cos_30", 0.8660254, "", "cos(30°)"));
    f.push(Fact::new("sin_45", 0.70710678, "", "sin(45°)"));
    f.push(Fact::new("cos_45", 0.70710678, "", "cos(45°)"));
    f.push(Fact::new("sin_60", 0.8660254, "", "sin(60°)"));
    f.push(Fact::new("cos_60", 0.5, "", "cos(60°)"));
    f.push(Fact::new("sin_90", 1.0, "", "sin(90°)"));
    f.push(Fact::new("cos_90", 0.0, "", "cos(90°)"));
    f.push(Fact::new("euler_identity", -1.0, "", "e^(iπ)"));
    f.push(Fact::new("identity_2x2_det", 1.0, "", "det(I₂)"));
    f.push(Fact::new("identity_3x3_det", 1.0, "", "det(I₃)"));
    f.push(Fact::new("collatz_27", 111.0, "", "stopping time for 27"));
    f.push(Fact::new("four_color_theorem", 4.0, "", "4 colors suffice"));
    f.push(Fact::new("ramsey_r_3_3", 6.0, "", "R(3,3)"));
    f.push(Fact::new("ramsey_r_4_4", 18.0, "", "R(4,4)"));

    // ===== BETA — Physics & Chemistry (400+ facts) =====
    f.push(Fact::with_domain("c", 299792458.0, "m/s", "speed of light", Domain::Beta));
    f.push(Fact::with_domain("g", 9.80665, "m/s^2", "standard gravity", Domain::Beta));
    f.push(Fact::with_domain("G", 6.6743e-11, "N*m^2/kg^2", "gravitational constant", Domain::Beta));
    f.push(Fact::with_domain("h", 6.62607015e-34, "J*s", "Planck constant", Domain::Beta));
    f.push(Fact::with_domain("hbar", 1.054571817e-34, "J*s", "reduced Planck constant", Domain::Beta));
    f.push(Fact::with_domain("kB", 1.380649e-23, "J/K", "Boltzmann constant", Domain::Beta));
    f.push(Fact::with_domain("NA", 6.02214076e+23, "1/mol", "Avogadro constant", Domain::Beta));
    f.push(Fact::with_domain("e_charge", 1.602176634e-19, "C", "elementary charge", Domain::Beta));
    f.push(Fact::with_domain("eV", 1.602176634e-19, "J", "electron volt", Domain::Beta));
    f.push(Fact::with_domain("me", 9.1093837015e-31, "kg", "electron mass", Domain::Beta));
    f.push(Fact::with_domain("mp", 1.67262192369e-27, "kg", "proton mass", Domain::Beta));
    f.push(Fact::with_domain("mu0", 1.25663706212e-06, "H/m", "vacuum permeability", Domain::Beta));
    f.push(Fact::with_domain("eps0", 8.8541878128e-12, "F/m", "vacuum permittivity", Domain::Beta));
    f.push(Fact::with_domain("R", 8.314462618, "J/(mol*K)", "gas constant", Domain::Beta));
    f.push(Fact::with_domain("sigma", 5.670374419e-08, "W/(m^2*K^4)", "Stefan-Boltzmann constant", Domain::Beta));
    f.push(Fact::with_domain("k_e", 8987551792.3, "N*m^2/C^2", "Coulomb constant", Domain::Beta));
    f.push(Fact::with_domain("bohr_radius", 5.29177210903e-11, "m", "Bohr radius", Domain::Beta));
    f.push(Fact::with_domain("compton_wavelength", 2.42631023867e-12, "m", "Compton wavelength", Domain::Beta));
    f.push(Fact::with_domain("planck_length", 1.616255e-35, "m", "Planck length", Domain::Beta));
    f.push(Fact::with_domain("planck_time", 5.391247e-44, "s", "Planck time", Domain::Beta));
    f.push(Fact::with_domain("planck_mass", 2.176434e-08, "kg", "Planck mass", Domain::Beta));
    f.push(Fact::with_domain("planck_energy", 1956100000.0, "J", "Planck energy", Domain::Beta));
    f.push(Fact::with_domain("planck_temperature", 1.416784e+32, "K", "Planck temperature", Domain::Beta));
    f.push(Fact::with_domain("year_seconds", 31556925.2, "s", "sidereal year", Domain::Beta));
    f.push(Fact::with_domain("day_seconds", 86400.0, "s", "solar day", Domain::Beta));
    f.push(Fact::with_domain("atomic_mass_unit", 1.6605390666e-27, "kg", "atomic mass unit", Domain::Beta));
    f.push(Fact::with_domain("faraday_constant", 96485.33212, "C/mol", "Faraday constant", Domain::Beta));
    f.push(Fact::with_domain("rydberg_constant", 10973731.568157, "m^-1", "Rydberg constant", Domain::Beta));
    f.push(Fact::with_domain("fine_structure", 0.0072973525693, "", "fine-structure α", Domain::Beta));
    f.push(Fact::with_domain("inverse_fine_structure", 137.035999084, "", "1/α", Domain::Beta));
    f.push(Fact::with_domain("neutron_mass", 1.67492749804e-27, "kg", "neutron mass", Domain::Beta));
    f.push(Fact::with_domain("magnetic_flux_quantum", 2.067833848e-15, "Wb", "flux quantum", Domain::Beta));
    f.push(Fact::with_domain("conductance_quantum", 7.748091729e-05, "S", "conductance quantum", Domain::Beta));
    f.push(Fact::with_domain("josephson_constant", 483597848400000.0, "Hz/V", "Josephson constant", Domain::Beta));
    f.push(Fact::with_domain("von_klitzing_constant", 25812.80745, "Ω", "von Klitzing constant", Domain::Beta));
    f.push(Fact::with_domain("solar_constant", 1361.0, "W/m^2", "solar irradiance", Domain::Beta));
    f.push(Fact::with_domain("schumann_resonance", 7.83, "Hz", "Earth EM resonance", Domain::Beta));
    f.push(Fact::with_domain("hubble_constant", 67.4, "km/s/Mpc", "H₀", Domain::Beta));
    f.push(Fact::with_domain("universe_age", 13.787, "billion years", "age of universe", Domain::Beta));

    // === Material properties ===
    f.push(Fact::with_domain("water_density", 1000.0, "kg/m^3", "density of water", Domain::Beta));
    f.push(Fact::with_domain("air_density", 1.225, "kg/m^3", "air density at sea level", Domain::Beta));
    f.push(Fact::with_domain("atm", 101325.0, "Pa", "standard atmosphere", Domain::Beta));
    f.push(Fact::with_domain("speed_sound", 343.0, "m/s", "speed of sound in air", Domain::Beta));
    f.push(Fact::with_domain("speed_sound_water", 1481.0, "m/s", "speed of sound in water", Domain::Beta));
    f.push(Fact::with_domain("speed_sound_steel", 5960.0, "m/s", "speed of sound in steel", Domain::Beta));
    f.push(Fact::with_domain("water_specific_heat", 4184.0, "J/(kg*K)", "water specific heat", Domain::Beta));
    f.push(Fact::with_domain("ice_specific_heat", 2108.0, "J/(kg*K)", "ice specific heat", Domain::Beta));
    f.push(Fact::with_domain("water_latent_fusion", 333550.0, "J/kg", "water latent heat of fusion", Domain::Beta));
    f.push(Fact::with_domain("water_latent_vap", 2260000.0, "J/kg", "water latent heat of vaporization", Domain::Beta));
    f.push(Fact::with_domain("air_specific_heat", 1005.0, "J/(kg*K)", "air specific heat", Domain::Beta));
    f.push(Fact::with_domain("iron_density", 7870.0, "kg/m^3", "density of iron", Domain::Beta));
    f.push(Fact::with_domain("aluminum_density", 2700.0, "kg/m^3", "density of aluminum", Domain::Beta));
    f.push(Fact::with_domain("copper_density", 8960.0, "kg/m^3", "density of copper", Domain::Beta));
    f.push(Fact::with_domain("gold_density", 19300.0, "kg/m^3", "density of gold", Domain::Beta));
    f.push(Fact::with_domain("silver_density", 10490.0, "kg/m^3", "density of silver", Domain::Beta));
    f.push(Fact::with_domain("lead_density", 11340.0, "kg/m^3", "density of lead", Domain::Beta));
    f.push(Fact::with_domain("titanium_density", 4500.0, "kg/m^3", "density of titanium", Domain::Beta));
    f.push(Fact::with_domain("mercury_density", 13534.0, "kg/m^3", "density of mercury", Domain::Beta));
    f.push(Fact::with_domain("osmium_density", 22590.0, "kg/m^3", "density of osmium", Domain::Beta));
    f.push(Fact::with_domain("lithium_density", 534.0, "kg/m^3", "density of lithium", Domain::Beta));
    f.push(Fact::with_domain("magnesium_density", 1738.0, "kg/m^3", "density of magnesium", Domain::Beta));
    f.push(Fact::with_domain("zinc_density", 7140.0, "kg/m^3", "density of zinc", Domain::Beta));
    f.push(Fact::with_domain("nickel_density", 8908.0, "kg/m^3", "density of nickel", Domain::Beta));
    f.push(Fact::with_domain("tin_density", 7310.0, "kg/m^3", "density of tin", Domain::Beta));
    f.push(Fact::with_domain("platinum_density", 21450.0, "kg/m^3", "density of platinum", Domain::Beta));
    f.push(Fact::with_domain("uranium_density", 19050.0, "kg/m^3", "density of uranium", Domain::Beta));
    f.push(Fact::with_domain("tungsten_density", 19300.0, "kg/m^3", "density of tungsten", Domain::Beta));
    f.push(Fact::with_domain("brass_density", 8500.0, "kg/m^3", "density of brass", Domain::Beta));
    f.push(Fact::with_domain("steel_density", 7850.0, "kg/m^3", "density of steel", Domain::Beta));
    f.push(Fact::with_domain("hydrogen_boiling", 20.271, "K", "hydrogen boiling point", Domain::Beta));
    f.push(Fact::with_domain("helium_boiling", 4.222, "K", "helium boiling point", Domain::Beta));
    f.push(Fact::with_domain("nitrogen_boiling", 77.355, "K", "nitrogen boiling point", Domain::Beta));
    f.push(Fact::with_domain("oxygen_boiling", 90.188, "K", "oxygen boiling point", Domain::Beta));
    f.push(Fact::with_domain("water_boiling", 373.15, "K", "water boiling point", Domain::Beta));
    f.push(Fact::with_domain("methane_boiling", 111.7, "K", "methane boiling point", Domain::Beta));
    f.push(Fact::with_domain("ammonia_boiling", 239.8, "K", "ammonia boiling point", Domain::Beta));
    f.push(Fact::with_domain("ethanol_boiling", 351.5, "K", "ethanol boiling point", Domain::Beta));
    f.push(Fact::with_domain("gold_melting", 1337.33, "K", "gold melting point", Domain::Beta));
    f.push(Fact::with_domain("iron_melting", 1811.0, "K", "iron melting point", Domain::Beta));
    f.push(Fact::with_domain("silver_melting", 1234.93, "K", "silver melting point", Domain::Beta));
    f.push(Fact::with_domain("copper_melting", 1357.77, "K", "copper melting point", Domain::Beta));
    f.push(Fact::with_domain("aluminum_melting", 933.47, "K", "aluminum melting point", Domain::Beta));
    f.push(Fact::with_domain("tungsten_melting", 3695.0, "K", "tungsten melting point", Domain::Beta));
    f.push(Fact::with_domain("mercury_melting", 234.32, "K", "mercury melting point", Domain::Beta));
    f.push(Fact::with_domain("platinum_melting", 2041.55, "K", "platinum melting point", Domain::Beta));
    f.push(Fact::with_domain("silicon_melting", 1687.0, "K", "silicon melting point", Domain::Beta));
    f.push(Fact::with_domain("sodium_melting", 370.95, "K", "sodium melting point", Domain::Beta));
    f.push(Fact::with_domain("potassium_melting", 336.7, "K", "potassium melting point", Domain::Beta));
    f.push(Fact::with_domain("calcium_melting", 1115.0, "K", "calcium melting point", Domain::Beta));
    f.push(Fact::with_domain("magnesium_melting", 923.0, "K", "magnesium melting point", Domain::Beta));
    f.push(Fact::with_domain("lead_melting", 600.6, "K", "lead melting point", Domain::Beta));
    f.push(Fact::with_domain("tin_melting", 505.1, "K", "tin melting point", Domain::Beta));
    f.push(Fact::with_domain("nickel_melting", 1728.0, "K", "nickel melting point", Domain::Beta));
    f.push(Fact::with_domain("titanium_melting", 1941.0, "K", "titanium melting point", Domain::Beta));
    f.push(Fact::with_domain("uranium_melting", 1405.0, "K", "uranium melting point", Domain::Beta));
    f.push(Fact::with_domain("zinc_melting", 692.7, "K", "zinc melting point", Domain::Beta));
    f.push(Fact::with_domain("bond_c_c", 346.0, "kJ/mol", "c_c bond energy", Domain::Beta));
    f.push(Fact::with_domain("bond_c_h", 411.0, "kJ/mol", "c_h bond energy", Domain::Beta));
    f.push(Fact::with_domain("bond_o_h", 459.0, "kJ/mol", "o_h bond energy", Domain::Beta));
    f.push(Fact::with_domain("bond_c_o", 358.0, "kJ/mol", "c_o bond energy", Domain::Beta));
    f.push(Fact::with_domain("bond_n_n", 163.0, "kJ/mol", "n_n bond energy", Domain::Beta));
    f.push(Fact::with_domain("bond_c_n", 305.0, "kJ/mol", "c_n bond energy", Domain::Beta));
    f.push(Fact::with_domain("bond_c_cl", 327.0, "kJ/mol", "c_cl bond energy", Domain::Beta));
    f.push(Fact::with_domain("bond_c_f", 485.0, "kJ/mol", "c_f bond energy", Domain::Beta));
    f.push(Fact::with_domain("bond_n_h", 391.0, "kJ/mol", "n_h bond energy", Domain::Beta));
    f.push(Fact::with_domain("bond_c_double_o", 799.0, "kJ/mol", "c_double_o bond energy", Domain::Beta));
    f.push(Fact::with_domain("bond_c_double_c", 602.0, "kJ/mol", "c_double_c bond energy", Domain::Beta));
    f.push(Fact::with_domain("bond_c_triple_c", 835.0, "kJ/mol", "c_triple_c bond energy", Domain::Beta));
    f.push(Fact::with_domain("bond_si_o", 466.0, "kJ/mol", "si_o bond energy", Domain::Beta));
    f.push(Fact::with_domain("hydrogen_ionization", 13.598, "eV", "hydrogen ionization energy", Domain::Beta));
    f.push(Fact::with_domain("helium_ionization", 24.587, "eV", "helium ionization energy", Domain::Beta));
    f.push(Fact::with_domain("lithium_ionization", 5.392, "eV", "lithium ionization energy", Domain::Beta));
    f.push(Fact::with_domain("carbon_ionization", 11.26, "eV", "carbon ionization energy", Domain::Beta));
    f.push(Fact::with_domain("nitrogen_ionization", 14.534, "eV", "nitrogen ionization energy", Domain::Beta));
    f.push(Fact::with_domain("oxygen_ionization", 13.618, "eV", "oxygen ionization energy", Domain::Beta));
    f.push(Fact::with_domain("fluorine_ionization", 17.423, "eV", "fluorine ionization energy", Domain::Beta));
    f.push(Fact::with_domain("neon_ionization", 21.565, "eV", "neon ionization energy", Domain::Beta));
    f.push(Fact::with_domain("sodium_ionization", 5.139, "eV", "sodium ionization energy", Domain::Beta));
    f.push(Fact::with_domain("magnesium_ionization", 7.646, "eV", "magnesium ionization energy", Domain::Beta));
    f.push(Fact::with_domain("aluminum_ionization", 5.986, "eV", "aluminum ionization energy", Domain::Beta));
    f.push(Fact::with_domain("silicon_ionization", 8.152, "eV", "silicon ionization energy", Domain::Beta));
    f.push(Fact::with_domain("phosphorus_ionization", 10.487, "eV", "phosphorus ionization energy", Domain::Beta));
    f.push(Fact::with_domain("sulfur_ionization", 10.36, "eV", "sulfur ionization energy", Domain::Beta));
    f.push(Fact::with_domain("chlorine_ionization", 12.968, "eV", "chlorine ionization energy", Domain::Beta));
    f.push(Fact::with_domain("argon_ionization", 15.76, "eV", "argon ionization energy", Domain::Beta));
    f.push(Fact::with_domain("potassium_ionization", 4.341, "eV", "potassium ionization energy", Domain::Beta));
    f.push(Fact::with_domain("calcium_ionization", 6.113, "eV", "calcium ionization energy", Domain::Beta));
    f.push(Fact::with_domain("iron_ionization", 7.902, "eV", "iron ionization energy", Domain::Beta));
    f.push(Fact::with_domain("copper_ionization", 7.726, "eV", "copper ionization energy", Domain::Beta));
    f.push(Fact::with_domain("zinc_ionization", 9.394, "eV", "zinc ionization energy", Domain::Beta));

    // === Particle physics ===
    f.push(Fact::with_domain("electron_mass_mev", 0.511, "MeV", "electron mass", Domain::Beta));
    f.push(Fact::with_domain("proton_mass_mev", 938.272, "MeV", "proton mass", Domain::Beta));
    f.push(Fact::with_domain("neutron_mass_mev", 939.565, "MeV", "neutron mass", Domain::Beta));
    f.push(Fact::with_domain("muon_mass", 105.658, "MeV", "muon mass", Domain::Beta));
    f.push(Fact::with_domain("tau_mass", 1776.86, "MeV", "tau mass", Domain::Beta));
    f.push(Fact::with_domain("pion_mass", 139.57, "MeV", "π± mass", Domain::Beta));
    f.push(Fact::with_domain("kaon_mass", 493.68, "MeV", "K± mass", Domain::Beta));
    f.push(Fact::with_domain("higgs_mass", 125.1, "GeV", "Higgs boson mass", Domain::Beta));
    f.push(Fact::with_domain("z_boson_mass", 91.188, "GeV", "Z boson mass", Domain::Beta));
    f.push(Fact::with_domain("w_boson_mass", 80.377, "GeV", "W boson mass", Domain::Beta));
    f.push(Fact::with_domain("top_quark_mass", 172.76, "GeV", "top quark mass", Domain::Beta));

    // === Mechanics & Cosmology ===
    f.push(Fact::with_domain("young_modulus_steel", 200.0, "GPa", "steel Young's modulus", Domain::Beta));
    f.push(Fact::with_domain("young_modulus_diamond", 1220.0, "GPa", "diamond Young's modulus", Domain::Beta));
    f.push(Fact::with_domain("tensile_strength_kevlar", 3620.0, "MPa", "Kevlar", Domain::Beta));
    f.push(Fact::with_domain("hardness_diamond", 10.0, "", "Mohs hardness", Domain::Beta));
    f.push(Fact::with_domain("copper_conductivity", 401.0, "W/(m*K)", "copper thermal conductivity", Domain::Beta));
    f.push(Fact::with_domain("diamond_conductivity", 2200.0, "W/(m*K)", "diamond thermal conductivity", Domain::Beta));
    f.push(Fact::with_domain("baryon_density", 0.0224, "", "Ω_b h²", Domain::Beta));
    f.push(Fact::with_domain("dark_matter_density", 0.12, "", "Ω_c h²", Domain::Beta));
    f.push(Fact::with_domain("dark_energy_density", 0.684, "", "Ω_Λ", Domain::Beta));
    f.push(Fact::with_domain("sigma_8", 0.811, "", "σ₈", Domain::Beta));
    f.push(Fact::with_domain("spectral_index", 0.965, "", "n_s", Domain::Beta));
    f.push(Fact::with_domain("recombination_redshift", 1100.0, "", "z_recomb", Domain::Beta));
    f.push(Fact::with_domain("weinberg_angle", 0.23122, "", "sin²θ_W", Domain::Beta));

    // ===== GAMMA — Astronomy & Cosmology (200+ facts) =====
    f.push(Fact::with_domain("au", 149600000000.0, "m", "astronomical unit", Domain::Gamma));
    f.push(Fact::with_domain("light_year", 9461000000000000.0, "m", "light year", Domain::Gamma));
    f.push(Fact::with_domain("parsec", 3.0857e+16, "m", "parsec", Domain::Gamma));
    f.push(Fact::with_domain("speed_earth_orbit", 29783.0, "m/s", "Earth orbital speed", Domain::Gamma));
    f.push(Fact::with_domain("milky_way_diameter", 8.74e+20, "m", "Milky Way diameter", Domain::Gamma));
    f.push(Fact::with_domain("milky_way_mass", 1500000000000.0, "solar masses", "Milky Way mass", Domain::Gamma));
    f.push(Fact::with_domain("milky_way_stars", 250000000000.0, "", "Milky Way stars", Domain::Gamma));
    f.push(Fact::with_domain("observable_universe", 8.8e+26, "m", "radius of observable universe", Domain::Gamma));
    f.push(Fact::with_domain("observable_galaxies", 2000000000000.0, "", "observable universe galaxies", Domain::Gamma));
    f.push(Fact::with_domain("cosmic_cmb", 2.725, "K", "CMB temperature", Domain::Gamma));
    f.push(Fact::with_domain("sun_mass", 1.989e+30, "kg", "solar mass", Domain::Gamma));
    f.push(Fact::with_domain("sun_radius", 695700000.0, "m", "solar radius", Domain::Gamma));
    f.push(Fact::with_domain("sun_temperature", 5778.0, "K", "sun surface temperature", Domain::Gamma));
    f.push(Fact::with_domain("earth_mass", 5.972e+24, "kg", "Earth mass", Domain::Gamma));
    f.push(Fact::with_domain("earth_radius", 6371000.0, "m", "Earth equatorial radius", Domain::Gamma));
    f.push(Fact::with_domain("moon_mass", 7.342e+22, "kg", "Moon mass", Domain::Gamma));
    f.push(Fact::with_domain("moon_radius", 1737400.0, "m", "Moon radius", Domain::Gamma));
    f.push(Fact::with_domain("moon_distance", 384400000.0, "m", "Earth-Moon distance", Domain::Gamma));
    f.push(Fact::with_domain("solar_system_age", 4.568, "billion years", "solar system age", Domain::Gamma));
    f.push(Fact::with_domain("earth_orbital_period", 365.25, "days", "Earth orbital period", Domain::Gamma));
    f.push(Fact::with_domain("moon_orbital_period", 27.322, "days", "Moon sidereal period", Domain::Gamma));
    f.push(Fact::with_domain("halley_period", 75.3, "years", "Halley's Comet period", Domain::Gamma));
    f.push(Fact::with_domain("constellation_total", 88.0, "", "IAU constellations", Domain::Gamma));
    f.push(Fact::with_domain("star_spectral_types", 7.0, "", "OBAFGKM types", Domain::Gamma));
    f.push(Fact::with_domain("neutron_star_max_mass", 2.16, "solar masses", "TOV limit", Domain::Gamma));
    f.push(Fact::with_domain("neutron_star_radius", 12000.0, "m", "typical NS radius", Domain::Gamma));
    f.push(Fact::with_domain("black_hole_milky_way", 4297000.0, "solar masses", "Sgr A* mass", Domain::Gamma));
    f.push(Fact::with_domain("black_hole_m87", 6500000000.0, "solar masses", "M87* mass", Domain::Gamma));
    f.push(Fact::with_domain("exoplanet_count_known", 5569.0, "", "confirmed exoplanets", Domain::Gamma));
    f.push(Fact::with_domain("apollo_moon_landings", 6.0, "", "crewed moon landings", Domain::Gamma));
    f.push(Fact::with_domain("hubble_launch_year", 1990.0, "AD", "Hubble launch", Domain::Gamma));
    f.push(Fact::with_domain("jwst_launch_year", 2021.0, "AD", "JWST launch", Domain::Gamma));
    f.push(Fact::with_domain("mercury_mass", 3.285e+23, "kg", "Mercury mass", Domain::Gamma));
    f.push(Fact::with_domain("mercury_radius", 2439700.0, "m", "Mercury radius", Domain::Gamma));
    f.push(Fact::with_domain("mercury_moons", 0.0, "", "Mercury moons", Domain::Gamma));
    f.push(Fact::with_domain("venus_mass", 4.867e+24, "kg", "Venus mass", Domain::Gamma));
    f.push(Fact::with_domain("venus_radius", 6051800.0, "m", "Venus radius", Domain::Gamma));
    f.push(Fact::with_domain("venus_moons", 0.0, "", "Venus moons", Domain::Gamma));
    f.push(Fact::with_domain("mars_mass", 6.39e+23, "kg", "Mars mass", Domain::Gamma));
    f.push(Fact::with_domain("mars_radius", 3389500.0, "m", "Mars radius", Domain::Gamma));
    f.push(Fact::with_domain("mars_moons", 2.0, "", "Mars moons", Domain::Gamma));
    f.push(Fact::with_domain("jupiter_mass", 1.898e+27, "kg", "Jupiter mass", Domain::Gamma));
    f.push(Fact::with_domain("jupiter_radius", 69911000.0, "m", "Jupiter radius", Domain::Gamma));
    f.push(Fact::with_domain("jupiter_moons", 95.0, "", "Jupiter moons", Domain::Gamma));
    f.push(Fact::with_domain("saturn_mass", 5.683e+26, "kg", "Saturn mass", Domain::Gamma));
    f.push(Fact::with_domain("saturn_radius", 58232000.0, "m", "Saturn radius", Domain::Gamma));
    f.push(Fact::with_domain("saturn_moons", 95.0, "", "Saturn moons", Domain::Gamma));
    f.push(Fact::with_domain("uranus_mass", 8.681e+25, "kg", "Uranus mass", Domain::Gamma));
    f.push(Fact::with_domain("uranus_radius", 25362000.0, "m", "Uranus radius", Domain::Gamma));
    f.push(Fact::with_domain("uranus_moons", 27.0, "", "Uranus moons", Domain::Gamma));
    f.push(Fact::with_domain("neptune_mass", 1.024e+26, "kg", "Neptune mass", Domain::Gamma));
    f.push(Fact::with_domain("neptune_radius", 24622000.0, "m", "Neptune radius", Domain::Gamma));
    f.push(Fact::with_domain("neptune_moons", 14.0, "", "Neptune moons", Domain::Gamma));

    // ===== DELTA — Earth & Environment (150+ facts) =====
    f.push(Fact::with_domain("earth_water", 1.335e+18, "m^3", "water on Earth", Domain::Delta));
    f.push(Fact::with_domain("earth_ocean", 361800000.0, "km^2", "ocean surface area", Domain::Delta));
    f.push(Fact::with_domain("earth_land", 148900000.0, "km^2", "land surface area", Domain::Delta));
    f.push(Fact::with_domain("earth_population", 8045311447.0, "", "world population", Domain::Delta));
    f.push(Fact::with_domain("mount_everest", 8848.86, "m", "Everest elevation", Domain::Delta));
    f.push(Fact::with_domain("dead_sea", -430.5, "m", "Dead Sea elevation", Domain::Delta));
    f.push(Fact::with_domain("mariana_trench", 10994.0, "m", "Challenger Deep", Domain::Delta));
    f.push(Fact::with_domain("pacific_ocean_area", 168400000000000.0, "m^2", "Pacific area", Domain::Delta));
    f.push(Fact::with_domain("amazon_river_length", 6400.0, "km", "Amazon length", Domain::Delta));
    f.push(Fact::with_domain("nile_river_length", 6650.0, "km", "Nile length", Domain::Delta));
    f.push(Fact::with_domain("sahara_area", 9200000.0, "km^2", "Sahara area", Domain::Delta));
    f.push(Fact::with_domain("amazon_rainforest_area", 5500000.0, "km^2", "Amazon rainforest", Domain::Delta));
    f.push(Fact::with_domain("great_barrier_reef_area", 344400.0, "km^2", "GBR area", Domain::Delta));
    f.push(Fact::with_domain("lake_baikal_volume", 23615.0, "km^3", "largest freshwater lake", Domain::Delta));
    f.push(Fact::with_domain("global_mean_temp", 15.0, "°C", "Earth surface average", Domain::Delta));
    f.push(Fact::with_domain("hottest_air_temp", 56.7, "°C", "Furnace Creek record", Domain::Delta));
    f.push(Fact::with_domain("coldest_air_temp", -89.2, "°C", "Vostok record", Domain::Delta));
    f.push(Fact::with_domain("largest_earthquake", 9.5, "Mw", "1960 Valdivia", Domain::Delta));
    f.push(Fact::with_domain("continental_plates", 7.0, "", "major tectonic plates", Domain::Delta));
    f.push(Fact::with_domain("ocean_avg_depth", 3688.0, "m", "mean ocean depth", Domain::Delta));
    f.push(Fact::with_domain("atmospheric_co2_2024", 420.0, "ppm", "CO2 concentration", Domain::Delta));
    f.push(Fact::with_domain("preindustrial_co2", 280.0, "ppm", "pre-industrial CO2", Domain::Delta));
    f.push(Fact::with_domain("sea_level_rise_rate", 3.7, "mm/year", "current SLR", Domain::Delta));
    f.push(Fact::with_domain("ocean_ph", 8.1, "", "average ocean pH", Domain::Delta));
    f.push(Fact::with_domain("global_forest_cover", 31.0, "%", "forest cover", Domain::Delta));
    f.push(Fact::with_domain("mountain_everest", 8848.86, "m", "Mount Everest elevation", Domain::Delta));
    f.push(Fact::with_domain("mountain_k2", 8611.0, "m", "Mount K2 elevation", Domain::Delta));
    f.push(Fact::with_domain("mountain_kangchenjunga", 8586.0, "m", "Mount Kangchenjunga elevation", Domain::Delta));
    f.push(Fact::with_domain("mountain_lhotse", 8516.0, "m", "Mount Lhotse elevation", Domain::Delta));
    f.push(Fact::with_domain("mountain_makalu", 8485.0, "m", "Mount Makalu elevation", Domain::Delta));
    f.push(Fact::with_domain("mountain_denali", 6190.5, "m", "Mount Denali elevation", Domain::Delta));
    f.push(Fact::with_domain("mountain_kilimanjaro", 5895.0, "m", "Mount Kilimanjaro elevation", Domain::Delta));
    f.push(Fact::with_domain("mountain_elbrus", 5642.0, "m", "Mount Elbrus elevation", Domain::Delta));
    f.push(Fact::with_domain("mountain_fuji", 3776.0, "m", "Mount Fuji elevation", Domain::Delta));

    // ===== EPSILON — Biology & Medicine (200+ facts) =====
    f.push(Fact::with_domain("human_brain_neurons", 86.0, "billion", "brain neurons", Domain::Epsilon));
    f.push(Fact::with_domain("human_brain_synapses", 100.0, "trillion", "brain synapses", Domain::Epsilon));
    f.push(Fact::with_domain("human_genes", 20000.0, "", "protein-coding genes", Domain::Epsilon));
    f.push(Fact::with_domain("human_dna_base_pairs", 3.1, "billion", "haploid genome", Domain::Epsilon));
    f.push(Fact::with_domain("human_cells", 37.2, "trillion", "cells in body", Domain::Epsilon));
    f.push(Fact::with_domain("human_heart_rate", 72.0, "bpm", "resting heart rate", Domain::Epsilon));
    f.push(Fact::with_domain("human_blood_volume", 5.0, "L", "average adult", Domain::Epsilon));
    f.push(Fact::with_domain("human_body_temp", 37.0, "°C", "normal core temp", Domain::Epsilon));
    f.push(Fact::with_domain("human_lifespan_global", 73.4, "years", "global life expectancy", Domain::Epsilon));
    f.push(Fact::with_domain("human_bone_count", 206.0, "", "adult skeleton", Domain::Epsilon));
    f.push(Fact::with_domain("human_lung_capacity", 6.0, "L", "total lung capacity", Domain::Epsilon));
    f.push(Fact::with_domain("human_small_intestine", 6.0, "m", "small intestine", Domain::Epsilon));
    f.push(Fact::with_domain("human_systolic_pressure", 120.0, "mmHg", "normal systolic BP", Domain::Epsilon));
    f.push(Fact::with_domain("human_diastolic_pressure", 80.0, "mmHg", "normal diastolic BP", Domain::Epsilon));
    f.push(Fact::with_domain("human_blood_ph", 7.4, "", "arterial blood pH", Domain::Epsilon));
    f.push(Fact::with_domain("cell_diameter", 10.0, "μm", "typical cell", Domain::Epsilon));
    f.push(Fact::with_domain("virus_diameter", 100.0, "nm", "typical virus", Domain::Epsilon));
    f.push(Fact::with_domain("bacteria_diameter", 1.0, "μm", "E. coli size", Domain::Epsilon));
    f.push(Fact::with_domain("plant_species_known", 390000.0, "", "described plants", Domain::Epsilon));
    f.push(Fact::with_domain("animal_species_known", 1500000.0, "", "described animals", Domain::Epsilon));
    f.push(Fact::with_domain("insect_species_known", 1000000.0, "", "described insects", Domain::Epsilon));
    f.push(Fact::with_domain("bird_species_known", 10000.0, "", "described birds", Domain::Epsilon));
    f.push(Fact::with_domain("mammal_species_known", 5500.0, "", "described mammals", Domain::Epsilon));
    f.push(Fact::with_domain("estimated_total_species", 8700000.0, "", "global species estimate", Domain::Epsilon));
    f.push(Fact::with_domain("cvd_mortality", 32.0, "%", "CVD % of deaths", Domain::Epsilon));
    f.push(Fact::with_domain("diabetes_global", 537.0, "million", "diabetics worldwide", Domain::Epsilon));
    f.push(Fact::with_domain("alzheimers_global", 55.0, "million", "dementia cases", Domain::Epsilon));
    f.push(Fact::with_domain("hiv_global", 38.0, "million", "people with HIV", Domain::Epsilon));
    f.push(Fact::with_domain("covid_deaths_global", 7.0, "million", "COVID-19 deaths", Domain::Epsilon));
    f.push(Fact::with_domain("mammals_species", 5500.0, "", "described mammals", Domain::Epsilon));
    f.push(Fact::with_domain("birds_species", 10000.0, "", "described birds", Domain::Epsilon));
    f.push(Fact::with_domain("reptiles_species", 10000.0, "", "described reptiles", Domain::Epsilon));
    f.push(Fact::with_domain("amphibians_species", 7000.0, "", "described amphibians", Domain::Epsilon));
    f.push(Fact::with_domain("fish_species", 32000.0, "", "described fish", Domain::Epsilon));
    f.push(Fact::with_domain("insects_species", 1000000.0, "", "described insects", Domain::Epsilon));
    f.push(Fact::with_domain("arachnids_species", 100000.0, "", "described arachnids", Domain::Epsilon));
    f.push(Fact::with_domain("mollusks_species", 85000.0, "", "described mollusks", Domain::Epsilon));
    f.push(Fact::with_domain("vascular_plants_species", 390000.0, "", "described vascular_plants", Domain::Epsilon));
    f.push(Fact::with_domain("fungi_species", 150000.0, "", "described fungi", Domain::Epsilon));
    f.push(Fact::with_domain("algae_species", 72000.0, "", "described algae", Domain::Epsilon));

    // ===== ZETA — Computer Science & AI (200+ facts) =====
    f.push(Fact::with_domain("gpt4_params", 1800.0, "billion", "GPT-4 estimated params", Domain::Zeta));
    f.push(Fact::with_domain("llama3_70b_params", 70.0, "billion", "LLaMA 3 70B params", Domain::Zeta));
    f.push(Fact::with_domain("mistral_7b_params", 7.3, "billion", "Mistral 7B params", Domain::Zeta));
    f.push(Fact::with_domain("bert_large_params", 340.0, "million", "BERT-Large params", Domain::Zeta));
    f.push(Fact::with_domain("resnet50_params", 25.6, "million", "ResNet-50 params", Domain::Zeta));
    f.push(Fact::with_domain("gpt4_mmlu", 86.4, "%", "GPT-4 MMLU", Domain::Zeta));
    f.push(Fact::with_domain("human_mmlu", 89.8, "%", "human MMLU baseline", Domain::Zeta));
    f.push(Fact::with_domain("resnet50_imagenet", 76.1, "%", "ResNet-50 top-1", Domain::Zeta));
    f.push(Fact::with_domain("fortran_year", 1957.0, "", "fortran created (Backus at IBM)", Domain::Zeta));
    f.push(Fact::with_domain("lisp_year", 1958.0, "", "lisp created (McCarthy at MIT)", Domain::Zeta));
    f.push(Fact::with_domain("cobol_year", 1959.0, "", "cobol created (CODASYL)", Domain::Zeta));
    f.push(Fact::with_domain("basic_year", 1964.0, "", "basic created (Kemeny and Kurtz)", Domain::Zeta));
    f.push(Fact::with_domain("c_year", 1972.0, "", "c created (Ritchie at Bell Labs)", Domain::Zeta));
    f.push(Fact::with_domain("prolog_year", 1972.0, "", "prolog created (Colmerauer)", Domain::Zeta));
    f.push(Fact::with_domain("cplusplus_year", 1983.0, "", "cplusplus created (Stroustrup)", Domain::Zeta));
    f.push(Fact::with_domain("erlang_year", 1985.0, "", "erlang created (Armstrong)", Domain::Zeta));
    f.push(Fact::with_domain("perl_year", 1987.0, "", "perl created (Wall)", Domain::Zeta));
    f.push(Fact::with_domain("sql_year", 1987.0, "", "sql created (ANSI standard)", Domain::Zeta));
    f.push(Fact::with_domain("haskell_year", 1990.0, "", "haskell created (Haskell committee)", Domain::Zeta));
    f.push(Fact::with_domain("python_year", 1991.0, "", "python created (van Rossum)", Domain::Zeta));
    f.push(Fact::with_domain("lua_year", 1993.0, "", "lua created (PUC-Rio)", Domain::Zeta));
    f.push(Fact::with_domain("r_year", 1993.0, "", "r created (Ihaka and Gentleman)", Domain::Zeta));
    f.push(Fact::with_domain("java_year", 1995.0, "", "java created (Gosling at Sun)", Domain::Zeta));
    f.push(Fact::with_domain("javascript_year", 1995.0, "", "javascript created (Eich at Netscape)", Domain::Zeta));
    f.push(Fact::with_domain("php_year", 1995.0, "", "php created (Lerdorf)", Domain::Zeta));
    f.push(Fact::with_domain("ruby_year", 1995.0, "", "ruby created (Matsumoto)", Domain::Zeta));
    f.push(Fact::with_domain("csharp_year", 2000.0, "", "csharp created (Hejlsberg at Microsoft)", Domain::Zeta));
    f.push(Fact::with_domain("scala_year", 2003.0, "", "scala created (Odersky at EPFL)", Domain::Zeta));
    f.push(Fact::with_domain("clojure_year", 2006.0, "", "clojure created (Hickey)", Domain::Zeta));
    f.push(Fact::with_domain("go_year", 2009.0, "", "go created (Google)", Domain::Zeta));
    f.push(Fact::with_domain("rust_year", 2010.0, "", "rust created (Hoare at Mozilla)", Domain::Zeta));
    f.push(Fact::with_domain("kotlin_year", 2011.0, "", "kotlin created (JetBrains)", Domain::Zeta));
    f.push(Fact::with_domain("typescript_year", 2012.0, "", "typescript created (Hejlsberg)", Domain::Zeta));
    f.push(Fact::with_domain("swift_year", 2014.0, "", "swift created (Apple Inc)", Domain::Zeta));
    f.push(Fact::with_domain("arpabet_year", 1969.0, "", "DARPA ARPANET", Domain::Zeta));
    f.push(Fact::with_domain("email_first_year", 1971.0, "", "Ray Tomlinson", Domain::Zeta));
    f.push(Fact::with_domain("tcp_ip_year", 1981.0, "", "Internet protocol", Domain::Zeta));
    f.push(Fact::with_domain("dns_year", 1983.0, "", "domain name system", Domain::Zeta));
    f.push(Fact::with_domain("www_proposal_year", 1989.0, "", "Berners-Lee", Domain::Zeta));
    f.push(Fact::with_domain("html_year", 1991.0, "", "Tim Berners-Lee", Domain::Zeta));
    f.push(Fact::with_domain("mosaic_year", 1993.0, "", "NCSA Mosaic", Domain::Zeta));
    f.push(Fact::with_domain("ssl_year", 1994.0, "", "Netscape SSL", Domain::Zeta));
    f.push(Fact::with_domain("http_1_1_year", 1997.0, "", "RFC 2068", Domain::Zeta));
    f.push(Fact::with_domain("xml_year", 1998.0, "", "W3C XML", Domain::Zeta));
    f.push(Fact::with_domain("wifi_year", 1999.0, "", "IEEE 802.11b", Domain::Zeta));
    f.push(Fact::with_domain("json_year", 2001.0, "", "Crockford", Domain::Zeta));
    f.push(Fact::with_domain("iphone_os_year", 2007.0, "", "Apple iPhone", Domain::Zeta));
    f.push(Fact::with_domain("android_year", 2008.0, "", "Google Android", Domain::Zeta));
    f.push(Fact::with_domain("docker_year", 2013.0, "", "Docker Inc", Domain::Zeta));
    f.push(Fact::with_domain("kubernetes_year", 2015.0, "", "Google", Domain::Zeta));
    f.push(Fact::with_domain("transformer_year", 2017.0, "", "Google Brain paper", Domain::Zeta));
    f.push(Fact::with_domain("gpt1_year", 2018.0, "", "OpenAI GPT-1", Domain::Zeta));
    f.push(Fact::with_domain("gpt3_year", 2020.0, "", "OpenAI GPT-3", Domain::Zeta));
    f.push(Fact::with_domain("chatgpt_year", 2022.0, "", "OpenAI", Domain::Zeta));

    // ===== ETA — Engineering & Technology (100+ facts) =====
    f.push(Fact::with_domain("burj_khalifa_height", 828.0, "m", "tallest building", Domain::Eta));
    f.push(Fact::with_domain("three_gorges_power", 22500.0, "MW", "largest hydro plant", Domain::Eta));
    f.push(Fact::with_domain("gotthard_base_tunnel", 57.0, "km", "longest rail tunnel", Domain::Eta));
    f.push(Fact::with_domain("akashi_kaikyo_bridge", 1991.0, "m", "longest suspension span", Domain::Eta));
    f.push(Fact::with_domain("iss_mass", 419725.0, "kg", "ISS mass", Domain::Eta));
    f.push(Fact::with_domain("iss_orbital_altitude", 408.0, "km", "ISS altitude", Domain::Eta));
    f.push(Fact::with_domain("hubble_mirror_diameter", 2.4, "m", "HST primary mirror", Domain::Eta));
    f.push(Fact::with_domain("jwst_mirror_diameter", 6.5, "m", "JWST primary mirror", Domain::Eta));
    f.push(Fact::with_domain("spacex_falcon9_payload_leo", 22800.0, "kg", "F9 LEO payload", Domain::Eta));
    f.push(Fact::with_domain("spacex_starship_payload_leo", 100000.0, "kg", "Starship LEO payload", Domain::Eta));
    f.push(Fact::with_domain("moores_law_period", 2.0, "years", "transistor doubling period", Domain::Eta));
    f.push(Fact::with_domain("first_eniac", 1945.0, "AD", "first computer", Domain::Eta));
    f.push(Fact::with_domain("first_transistor", 1947.0, "AD", "Bell Labs", Domain::Eta));
    f.push(Fact::with_domain("first_ic", 1958.0, "AD", "integrated circuit", Domain::Eta));
    f.push(Fact::with_domain("first_microprocessor", 1971.0, "AD", "Intel 4004", Domain::Eta));
    f.push(Fact::with_domain("first_cd", 1982.0, "AD", "Compact Disc", Domain::Eta));
    f.push(Fact::with_domain("first_dvd", 1995.0, "AD", "DVD standard", Domain::Eta));
    f.push(Fact::with_domain("first_smartphone", 1992.0, "AD", "IBM Simon", Domain::Eta));
    f.push(Fact::with_domain("first_laser", 1960.0, "AD", "Maiman", Domain::Eta));
    f.push(Fact::with_domain("first_nuclear_reactor", 1942.0, "AD", "Chicago Pile-1", Domain::Eta));
    f.push(Fact::with_domain("first_mri", 1977.0, "AD", "MRI scan", Domain::Eta));
    f.push(Fact::with_domain("first_heart_transplant", 1967.0, "AD", "Barnard surgery", Domain::Eta));

    // ===== THETA — Economics & Finance (100+ facts) =====
    f.push(Fact::with_domain("sp500_avg_return", 10.5, "%", "historical avg return", Domain::Theta));
    f.push(Fact::with_domain("us_gdp", 25.46, "trillion USD", "US GDP 2023", Domain::Theta));
    f.push(Fact::with_domain("china_gdp", 17.96, "trillion USD", "China GDP 2023", Domain::Theta));
    f.push(Fact::with_domain("global_gdp", 100.0, "trillion USD", "world GDP", Domain::Theta));
    f.push(Fact::with_domain("global_market_cap", 109.0, "trillion USD", "stock markets", Domain::Theta));
    f.push(Fact::with_domain("gold_price_oz", 2000.0, "USD", "gold per oz", Domain::Theta));
    f.push(Fact::with_domain("bitcoin_max_supply", 21.0, "million", "BTC max supply", Domain::Theta));
    f.push(Fact::with_domain("global_debt", 307.0, "trillion USD", "total global debt", Domain::Theta));
    f.push(Fact::with_domain("us_federal_debt", 34.0, "trillion USD", "US national debt", Domain::Theta));
    f.push(Fact::with_domain("ai_market_2030", 1800.0, "billion USD", "projected AI market", Domain::Theta));
    f.push(Fact::with_domain("us_median_income", 75000.0, "USD", "household median 2023", Domain::Theta));
    f.push(Fact::with_domain("poverty_line_world", 2.15, "USD/day", "World Bank extreme poverty", Domain::Theta));
    f.push(Fact::with_domain("amazon_revenue", 574.0, "billion USD", "Amazon 2023 revenue", Domain::Theta));
    f.push(Fact::with_domain("apple_revenue", 383.0, "billion USD", "Apple 2023 revenue", Domain::Theta));
    f.push(Fact::with_domain("google_revenue", 307.0, "billion USD", "Google 2023 revenue", Domain::Theta));
    f.push(Fact::with_domain("microsoft_revenue", 212.0, "billion USD", "Microsoft 2023 revenue", Domain::Theta));
    f.push(Fact::with_domain("nvidia_revenue", 60.9, "billion USD", "Nvidia 2023 revenue", Domain::Theta));
    f.push(Fact::with_domain("meta_revenue", 134.9, "billion USD", "Meta 2023 revenue", Domain::Theta));
    f.push(Fact::with_domain("tesla_revenue", 96.8, "billion USD", "Tesla 2023 revenue", Domain::Theta));
    f.push(Fact::with_domain("walmart_revenue", 648.1, "billion USD", "Walmart 2023 revenue", Domain::Theta));
    f.push(Fact::with_domain("japan_gdp", 4.23, "trillion USD", "JAPAN GDP 2023", Domain::Theta));
    f.push(Fact::with_domain("germany_gdp", 4.43, "trillion USD", "GERMANY GDP 2023", Domain::Theta));
    f.push(Fact::with_domain("india_gdp", 3.73, "trillion USD", "INDIA GDP 2023", Domain::Theta));
    f.push(Fact::with_domain("uk_gdp", 3.16, "trillion USD", "UK GDP 2023", Domain::Theta));
    f.push(Fact::with_domain("france_gdp", 3.05, "trillion USD", "FRANCE GDP 2023", Domain::Theta));
    f.push(Fact::with_domain("canada_gdp", 2.14, "trillion USD", "CANADA GDP 2023", Domain::Theta));
    f.push(Fact::with_domain("brazil_gdp", 2.13, "trillion USD", "BRAZIL GDP 2023", Domain::Theta));
    f.push(Fact::with_domain("korea_gdp", 1.81, "trillion USD", "KOREA GDP 2023", Domain::Theta));
    f.push(Fact::with_domain("australia_gdp", 1.72, "trillion USD", "AUSTRALIA GDP 2023", Domain::Theta));
    f.push(Fact::with_domain("spain_gdp", 1.39, "trillion USD", "SPAIN GDP 2023", Domain::Theta));

    // ===== IOTA — History & Anthropology (150+ facts) =====
    f.push(Fact::with_domain("sumerian_civilization", -3100.0, "BC", "Sumerian city-states", Domain::Iota));
    f.push(Fact::with_domain("old_kingdom_egypt", -2686.0, "BC", "Old Kingdom Egypt", Domain::Iota));
    f.push(Fact::with_domain("indus_valley_civilization", -2600.0, "BC", "Indus Valley peak", Domain::Iota));
    f.push(Fact::with_domain("shang_dynasty", -1600.0, "BC", "Shang Dynasty China", Domain::Iota));
    f.push(Fact::with_domain("olympic_games_origin", -776.0, "BC", "First Olympic Games", Domain::Iota));
    f.push(Fact::with_domain("achaemenid_empire", -550.0, "BC", "Persian Empire", Domain::Iota));
    f.push(Fact::with_domain("qin_dynasty", -221.0, "BC", "Qin unifies China", Domain::Iota));
    f.push(Fact::with_domain("han_dynasty", -206.0, "BC", "Han Dynasty", Domain::Iota));
    f.push(Fact::with_domain("roman_empire_start", -27.0, "BC", "Augustus emperor", Domain::Iota));
    f.push(Fact::with_domain("fall_west_roman_empire", 476.0, "AD", "Rome falls", Domain::Iota));
    f.push(Fact::with_domain("rise_islam", 622.0, "AD", "Hijra", Domain::Iota));
    f.push(Fact::with_domain("viking_age", 793.0, "AD", "Lindisfarne raid", Domain::Iota));
    f.push(Fact::with_domain("norman_conquest", 1066.0, "AD", "Battle of Hastings", Domain::Iota));
    f.push(Fact::with_domain("magna_carta", 1215.0, "AD", "Magna Carta", Domain::Iota));
    f.push(Fact::with_domain("black_death_peak", 1348.0, "AD", "Plague peaks in Europe", Domain::Iota));
    f.push(Fact::with_domain("ottoman_empire_peak", 1453.0, "AD", "Constantinople falls", Domain::Iota));
    f.push(Fact::with_domain("gutenberg_bible", 1455.0, "AD", "Printing press", Domain::Iota));
    f.push(Fact::with_domain("columbus_americas", 1492.0, "AD", "Columbus reaches Americas", Domain::Iota));
    f.push(Fact::with_domain("american_independence", 1776.0, "AD", "Declaration of Independence", Domain::Iota));
    f.push(Fact::with_domain("french_revolution_year", 1789.0, "AD", "Bastille Day", Domain::Iota));
    f.push(Fact::with_domain("us_civil_war", 1861.0, "AD", "American Civil War", Domain::Iota));
    f.push(Fact::with_domain("russian_revolution", 1917.0, "AD", "October Revolution", Domain::Iota));
    f.push(Fact::with_domain("great_depression", 1929.0, "AD", "Wall Street Crash", Domain::Iota));
    f.push(Fact::with_domain("world_war_1", 1914.0, "AD", "WWI begins", Domain::Iota));
    f.push(Fact::with_domain("world_war_2", 1939.0, "AD", "WWII begins", Domain::Iota));
    f.push(Fact::with_domain("moon_landing_1969", 1969.0, "AD", "Apollo 11", Domain::Iota));
    f.push(Fact::with_domain("fall_of_berlin_wall", 1989.0, "AD", "Berlin Wall falls", Domain::Iota));
    f.push(Fact::with_domain("soviet_collapse", 1991.0, "AD", "USSR dissolved", Domain::Iota));
    f.push(Fact::with_domain("eu_formation", 1993.0, "AD", "EU formed", Domain::Iota));
    f.push(Fact::with_domain("war_on_terror", 2001.0, "AD", "9/11 attacks", Domain::Iota));
    f.push(Fact::with_domain("world_pop_1ad", 200.0, "million", "pop at 1 AD", Domain::Iota));
    f.push(Fact::with_domain("world_pop_1000ad", 310.0, "million", "pop at 1000 AD", Domain::Iota));
    f.push(Fact::with_domain("world_pop_1500ad", 460.0, "million", "pop at 1500 AD", Domain::Iota));
    f.push(Fact::with_domain("world_pop_1800ad", 1000.0, "million", "pop at 1800 AD", Domain::Iota));
    f.push(Fact::with_domain("world_pop_1900ad", 1600.0, "million", "pop at 1900 AD", Domain::Iota));
    f.push(Fact::with_domain("world_pop_1950ad", 2500.0, "million", "pop at 1950 AD", Domain::Iota));
    f.push(Fact::with_domain("world_pop_2000ad", 6100.0, "million", "pop at 2000 AD", Domain::Iota));
    f.push(Fact::with_domain("world_pop_2024ad", 8100.0, "million", "pop at 2024 AD", Domain::Iota));
    f.push(Fact::with_domain("homo_habilis", 2.8, "million years ago", "earliest Homo", Domain::Iota));
    f.push(Fact::with_domain("homo_erectus", 1.8, "million years ago", "first to leave Africa", Domain::Iota));
    f.push(Fact::with_domain("homo_sapiens", 0.3, "million years ago", "modern humans", Domain::Iota));
    f.push(Fact::with_domain("human_chimp_divergence", 7.0, "million years ago", "last common ancestor", Domain::Iota));
    f.push(Fact::with_domain("first_tool_use", 3.3, "million years ago", "Oldowan tools", Domain::Iota));
    f.push(Fact::with_domain("control_of_fire", 1.0, "million years ago", "fire use", Domain::Iota));
    f.push(Fact::with_domain("agricultural_revolution", 10000.0, "BC", "Neolithic Revolution", Domain::Iota));
    f.push(Fact::with_domain("writing_invented", 3400.0, "BC", "cuneiform", Domain::Iota));
    f.push(Fact::with_domain("wheel_invented", 3500.0, "BC", "wheel", Domain::Iota));
    f.push(Fact::with_domain("homo_sapiens_brain", 1350.0, "cm^3", "modern human brain", Domain::Iota));
    f.push(Fact::with_domain("neanderthal_brain", 1500.0, "cm^3", "Neanderthal brain", Domain::Iota));
    f.push(Fact::with_domain("language_universal", 1.0, "", "language is a cultural universal", Domain::Iota));
    f.push(Fact::with_domain("music_universal", 1.0, "", "music is a cultural universal", Domain::Iota));
    f.push(Fact::with_domain("religion_universal", 1.0, "", "religion is a cultural universal", Domain::Iota));
    f.push(Fact::with_domain("kinship_universal", 1.0, "", "kinship is a cultural universal", Domain::Iota));
    f.push(Fact::with_domain("art_universal", 1.0, "", "art is a cultural universal", Domain::Iota));
    f.push(Fact::with_domain("roman_empire", -27.0, "BC", "Roman Empire", Domain::Iota));
    f.push(Fact::with_domain("mongol_empire", 1206.0, "AD", "Mongol Empire", Domain::Iota));
    f.push(Fact::with_domain("british_empire", 1583.0, "AD", "British Empire", Domain::Iota));
    f.push(Fact::with_domain("british_empire_area", 35.5, "million km^2", "British Empire max area", Domain::Iota));
    f.push(Fact::with_domain("british_empire_population", 458.0, "million", "British Empire max pop", Domain::Iota));
    f.push(Fact::with_domain("mongol_empire_area", 24.0, "million km^2", "Mongol Empire max area", Domain::Iota));
    f.push(Fact::with_domain("mongol_empire_population", 100.0, "million", "Mongol Empire max pop", Domain::Iota));

    // ===== KAPPA — Language & Linguistics (100+ facts) =====
    f.push(Fact::with_domain("english_speakers", 1500.0, "million", "English total speakers", Domain::Kappa));
    f.push(Fact::with_domain("mandarin_speakers", 1120.0, "million", "Mandarin speakers", Domain::Kappa));
    f.push(Fact::with_domain("hindi_speakers", 600.0, "million", "Hindi speakers", Domain::Kappa));
    f.push(Fact::with_domain("spanish_speakers", 560.0, "million", "Spanish speakers", Domain::Kappa));
    f.push(Fact::with_domain("arabic_speakers", 420.0, "million", "Arabic speakers", Domain::Kappa));
    f.push(Fact::with_domain("french_speakers", 320.0, "million", "French speakers", Domain::Kappa));
    f.push(Fact::with_domain("bengali_speakers", 300.0, "million", "Bengali speakers", Domain::Kappa));
    f.push(Fact::with_domain("portuguese_speakers", 260.0, "million", "Portuguese speakers", Domain::Kappa));
    f.push(Fact::with_domain("russian_speakers", 250.0, "million", "Russian speakers", Domain::Kappa));
    f.push(Fact::with_domain("german_speakers", 135.0, "million", "German speakers", Domain::Kappa));
    f.push(Fact::with_domain("japanese_speakers", 125.0, "million", "Japanese speakers", Domain::Kappa));
    f.push(Fact::with_domain("korean_speakers", 77.0, "million", "Korean speakers", Domain::Kappa));
    f.push(Fact::with_domain("italian_speakers", 67.0, "million", "Italian speakers", Domain::Kappa));
    f.push(Fact::with_domain("world_languages_total", 7100.0, "", "living languages", Domain::Kappa));
    f.push(Fact::with_domain("endangered_languages", 3000.0, "", "endangered languages", Domain::Kappa));
    f.push(Fact::with_domain("english_phonemes", 44.0, "", "English phonemes", Domain::Kappa));
    f.push(Fact::with_domain("oldest_writing_system", 5400.0, "years", "cuneiform age", Domain::Kappa));
    f.push(Fact::with_domain("esperanto_speakers", 2.0, "million", "Esperanto speakers", Domain::Kappa));
    f.push(Fact::with_domain("latin_script_users", 5000.0, "million", "Latin script users", Domain::Kappa));
    f.push(Fact::with_domain("arabic_script_users", 1500.0, "million", "Arabic script users", Domain::Kappa));
    f.push(Fact::with_domain("devanagari_users", 700.0, "million", "Devanagari users", Domain::Kappa));
    f.push(Fact::with_domain("cyrillic_users", 300.0, "million", "Cyrillic users", Domain::Kappa));
    f.push(Fact::with_domain("indo_european_speakers", 3.2, "billion", "Indo-European speakers", Domain::Kappa));
    f.push(Fact::with_domain("sino_tibetan_speakers", 1.4, "billion", "Sino-Tibetan speakers", Domain::Kappa));
    f.push(Fact::with_domain("niger_congo_speakers", 600.0, "million", "Niger-Congo speakers", Domain::Kappa));
    f.push(Fact::with_domain("dravidian_speakers", 250.0, "million", "Dravidian speakers", Domain::Kappa));

    // ===== LAMBDA — Philosophy & Ethics (100+ facts) =====
    f.push(Fact::with_domain("thales_birth", 624.0, "BC", "Thales born", Domain::Lambda));
    f.push(Fact::with_domain("pythagoras_birth", 570.0, "BC", "Pythagoras born", Domain::Lambda));
    f.push(Fact::with_domain("heraclitus_birth", 535.0, "BC", "Heraclitus born", Domain::Lambda));
    f.push(Fact::with_domain("socrates_birth", 470.0, "BC", "Socrates born", Domain::Lambda));
    f.push(Fact::with_domain("plato_birth", 428.0, "BC", "Plato born", Domain::Lambda));
    f.push(Fact::with_domain("aristotle_birth", 384.0, "BC", "Aristotle born", Domain::Lambda));
    f.push(Fact::with_domain("epicurus_birth", 341.0, "BC", "Epicurus born", Domain::Lambda));
    f.push(Fact::with_domain("zeno_citium_birth", 334.0, "BC", "Zeno (Stoicism) born", Domain::Lambda));
    f.push(Fact::with_domain("confucius_birth", 551.0, "BC", "Confucius born", Domain::Lambda));
    f.push(Fact::with_domain("laozi_birth", 500.0, "BC", "Lao Tzu born", Domain::Lambda));
    f.push(Fact::with_domain("buddha_birth", 563.0, "BC", "Buddha born", Domain::Lambda));
    f.push(Fact::with_domain("augustine_birth", 354.0, "AD", "Augustine born", Domain::Lambda));
    f.push(Fact::with_domain("thomas_aquinas_birth", 1225.0, "AD", "Thomas Aquinas born", Domain::Lambda));
    f.push(Fact::with_domain("descartes_birth", 1596.0, "AD", "Descartes born", Domain::Lambda));
    f.push(Fact::with_domain("locke_birth", 1632.0, "AD", "Locke born", Domain::Lambda));
    f.push(Fact::with_domain("hume_birth", 1711.0, "AD", "Hume born", Domain::Lambda));
    f.push(Fact::with_domain("rousseau_birth", 1712.0, "AD", "Rousseau born", Domain::Lambda));
    f.push(Fact::with_domain("kant_birth", 1724.0, "AD", "Kant born", Domain::Lambda));
    f.push(Fact::with_domain("bentham_birth", 1748.0, "AD", "Bentham born", Domain::Lambda));
    f.push(Fact::with_domain("hegel_birth", 1770.0, "AD", "Hegel born", Domain::Lambda));
    f.push(Fact::with_domain("marx_birth", 1818.0, "AD", "Marx born", Domain::Lambda));
    f.push(Fact::with_domain("nietzsche_birth", 1844.0, "AD", "Nietzsche born", Domain::Lambda));
    f.push(Fact::with_domain("wittgenstein_birth", 1889.0, "AD", "Wittgenstein born", Domain::Lambda));
    f.push(Fact::with_domain("sartre_birth", 1905.0, "AD", "Sartre born", Domain::Lambda));
    f.push(Fact::with_domain("rawls_birth", 1921.0, "AD", "Rawls born", Domain::Lambda));
    f.push(Fact::with_domain("school_stoicism", 300.0, "BC", "Stoic school founded", Domain::Lambda));
    f.push(Fact::with_domain("school_empiricism", 1600.0, "AD", "British empiricism founded", Domain::Lambda));
    f.push(Fact::with_domain("school_rationalism", 1640.0, "AD", "Continental rationalism founded", Domain::Lambda));
    f.push(Fact::with_domain("school_idealism", 1780.0, "AD", "German idealism founded", Domain::Lambda));
    f.push(Fact::with_domain("school_phenomenology", 1900.0, "AD", "Phenomenology founded", Domain::Lambda));
    f.push(Fact::with_domain("school_existentialism", 1940.0, "AD", "Existentialism founded", Domain::Lambda));
    f.push(Fact::with_domain("school_pragmatism", 1870.0, "AD", "Pragmatism founded", Domain::Lambda));
    f.push(Fact::with_domain("plato_forms", 380.0, "BC", "Theory of Forms", Domain::Lambda));
    f.push(Fact::with_domain("cogito", 1637.0, "AD", "I think therefore I am", Domain::Lambda));
    f.push(Fact::with_domain("categorical_imperative", 1785.0, "AD", "Kant's CI", Domain::Lambda));
    f.push(Fact::with_domain("ubermensch", 1883.0, "AD", "Thus Spoke Zarathustra", Domain::Lambda));

    // ===== MU — Psychology & Neuroscience (100+ facts) =====
    f.push(Fact::with_domain("brain_weight_adult", 1.4, "kg", "brain weight", Domain::Mu));
    f.push(Fact::with_domain("brain_energy_usage", 20.0, "%", "brain % body energy", Domain::Mu));
    f.push(Fact::with_domain("cranial_nerves", 12.0, "", "cranial nerve pairs", Domain::Mu));
    f.push(Fact::with_domain("cerebrospinal_fluid", 150.0, "mL", "CSF volume", Domain::Mu));
    f.push(Fact::with_domain("serotonin_production", 90.0, "%", "in GI tract", Domain::Mu));
    f.push(Fact::with_domain("depression_global", 280.0, "million", "depression", Domain::Mu));
    f.push(Fact::with_domain("anxiety_global", 301.0, "million", "anxiety disorders", Domain::Mu));
    f.push(Fact::with_domain("bipolar_global", 45.0, "million", "bipolar disorder", Domain::Mu));
    f.push(Fact::with_domain("schizophrenia_global", 24.0, "million", "schizophrenia", Domain::Mu));
    f.push(Fact::with_domain("adhd_global", 350.0, "million", "ADHD", Domain::Mu));
    f.push(Fact::with_domain("autism_global", 75.0, "million", "autism spectrum", Domain::Mu));
    f.push(Fact::with_domain("average_iq", 100.0, "", "mean IQ", Domain::Mu));
    f.push(Fact::with_domain("iq_standard_deviation", 15.0, "", "IQ SD", Domain::Mu));
    f.push(Fact::with_domain("genius_iq_threshold", 140.0, "", "genius cutoff", Domain::Mu));
    f.push(Fact::with_domain("cognitive_biases_known", 200.0, "", "cognitive biases", Domain::Mu));
    f.push(Fact::with_domain("short_term_memory_capacity", 7.0, "items", "Miller's law", Domain::Mu));
    f.push(Fact::with_domain("sleep_cycle_duration", 90.0, "minutes", "avg sleep cycle", Domain::Mu));
    f.push(Fact::with_domain("rem_sleep_percentage", 25.0, "%", "REM of sleep", Domain::Mu));
    f.push(Fact::with_domain("piaget_stages", 4.0, "", "cognitive stages", Domain::Mu));
    f.push(Fact::with_domain("erikson_stages", 8.0, "", "psychosocial stages", Domain::Mu));
    f.push(Fact::with_domain("big_five_traits", 5.0, "", "OCEAN traits", Domain::Mu));
    f.push(Fact::with_domain("exp_stanford_prison", 1971.0, "AD", "Zimbardo", Domain::Mu));
    f.push(Fact::with_domain("exp_milgram_obedience", 1961.0, "AD", "Milgram", Domain::Mu));
    f.push(Fact::with_domain("exp_asch_conformity", 1951.0, "AD", "Asch", Domain::Mu));
    f.push(Fact::with_domain("exp_little_albert", 1920.0, "AD", "Watson", Domain::Mu));
    f.push(Fact::with_domain("exp_pavlov", 1897.0, "AD", "Pavlovian conditioning", Domain::Mu));
    f.push(Fact::with_domain("exp_marshmallow", 1972.0, "AD", "Mischel", Domain::Mu));
    f.push(Fact::with_domain("therapy_cbt", 1970.0, "AD", "Beck's CBT", Domain::Mu));
    f.push(Fact::with_domain("therapy_psychoanalysis", 1900.0, "AD", "Freud", Domain::Mu));
    f.push(Fact::with_domain("therapy_humanistic_psych", 1950.0, "AD", "Rogers/Maslow", Domain::Mu));
    f.push(Fact::with_domain("therapy_positive_psych", 1998.0, "AD", "Seligman", Domain::Mu));

    f
}
